# encodings: utf-8
# audio_format: mp3, flac
# artwork_img_format: png, jpg

PRINT_CFG:
  lyrics: True
  artwork: True
  encoding: True

CALC_CFG:
  lyrics: True
  encoding: utf-8
  ARTWORK:
    artwork: True
    artwork_width: 800
    artwork_height: 800
    artwork_img_format: png
  audio_format: mp3
  missing_releases: True